### ISSUE TITLE
Unable to uninstall `Bootloader Application Interface` component in SDK 4.1.0

### ISSUE THREAD

**Issue by kriszabala** [SiliconLabs/gecko_sdk#15]
We have a working project based on the Bluetooth-NCP example using Gecko SDK 4.0.2 to build firmware for EFR32. Our current configuration removes the `Platform->Bootloader->Bootloader Application Interface` component. This builds with no issues with SDK 4.0.2.

We are running into an issue attempting to update the SDK to 4.1.0 as the `Bootloader Application Interface` component is now showing up as a dependency of the `NCP Interface` and can no longer be uninstalled.

<img width="1258" alt="Screen Shot 2022-08-08 at 4 24 56 PM" src="https://user-images.githubusercontent.com/153799/183508484-2ae4fcb3-5da4-4312-b08f-c717956ee24e.png">

**Comment by silabs-DenverL** [comment]
Do you still have the issue on GSDK 4.1.3?
![image](https://user-images.githubusercontent.com/49192521/198184397-16d94b09-3572-4da6-9608-a74fbb9c9a16.png)

**Comment by kriszabala** [comment]
Just tried it and looks like it's fixed in 4.1.3. Thanks
