### ISSUE TITLE
Missing linker scripts for series 2 chip 4

### ISSUE THREAD

**Issue by FredrikLL** [SiliconLabs/gecko_sdk#21]
The linker scripts for BGM24, MGM24, and EFR32BG24 are missing. They are usually found under 'platform/Device/SiliconLabs/<die>/Source/GCC' but for these dies it seems that they are not there. 
It exist for EFR32MG24 though, I assume it would be the same, but it makes generating paths via substitution wonky.

**Comment by silabs-DenverL** [comment]
What do you mean by linker file?

If you mean the *ld linker file for a device, AFAIK silabs did not put that file in the folder you mentioned.
If you create a project in Simplicity Studio, you could see the linker file automatically generated.

![image](https://user-images.githubusercontent.com/49192521/192417475-0d5ce969-d58e-474b-b821-6fad06356826.png)

**Comment by FredrikLL** [comment]
I mean the linker scripts (*.ld) files. 

I think it has been left out for some chips (eg. EFR32BG24). 
If you look at 'platform/Device/SiliconLabs/EFR32MG24/Source/' there is a folder called 'GCC' containing startup file in assembly and the linker script file, but in 'platform/Device/SiliconLabs/EFR32BG24/Source/' there is no 'GCC' folder.
