### ISSUE TITLE
Issue with Zwave 800 Series

### ISSUE THREAD

**Issue by SYESHASWINI** [SiliconLabs/gecko_sdk#48]
I'm using gecko_sdk version: 4.2.3
hardware: ZGM230S radio board
example: Zwave_soc_switchOnOff
The program is built and flashed with no errors.  When open launch console, no print statements are prints( debugprint is enabled). It seems like the code is flashed but not running.

**Comment by ADC-AHayden** [comment]
Did you flash it with an OTA bootloader? There is a prebuilt one you can flash if you search for "Z-Wave ota" in the example projects & demos.

There are also instructions for building the bootloader in [this Silabs knowledge article](https://community.silabs.com/s/article/Creating-OTA-bootloader-for-Z-Wave-800-series?language=en_US).

**Comment by LanKuoWei** [comment]
Please follow the instructions, I think there should be no problem.

**Comment by SYESHASWINI** [comment]
@ADC-AHayden  The article refers 4.1.x version as the version I use is 4.2.3 so can I go with this, because the below options are missing in the configuration.
>Install Bootloader > Core > GBL Compression (LZMA) component for Z-Wave 800 series.
>Install Bootloader > Utils > Application upgrade version check component.

When I enable the other configurations and build the project it throws few header file errors.

**Comment by SYESHASWINI** [comment]
@ADC-AHayden I tried the process with version 4.1.1
I first uploaded the hex file of the bootloader and then uploaded the hex file of the project, but unable to run the program.
Is there any things need to be added or another procedure required for it.

**Comment by LanKuoWei** [comment]
Note that it still needs to match the SE version.

**Comment by SYESHASWINI** [comment]
@LanKuoWei Where can I check the **SE version**. Is the way of adding bootloader to the project is right?

**Comment by LanKuoWei** [comment]
You can check [GSDK_v4.X.X\util\se_release\public], the file name is "s2c3_se_fw_upgrade_app_2v2p0.hex", which means v2.2.0, if the SE does not match, the SDK may not work properly, but there is another point to note that it can only Upgrade instead of downgrade.

Please refer to "UG162", there are commands to read SE version and upgrade.

**Comment by SYESHASWINI** [comment]
secure fw version is 2.2.1 which is latest and for 4.1.1 it is 2.2.0 which is a mismatch, can we resolve this anyway as downgrade doesn't work

**Comment by LanKuoWei** [comment]
(1) I use a simpler method in the old SDK version, if it is ZGM230S, directly use the sample "ota-ZGM230S_BRD4205B-crc.s37", but in the latest GSDK 4.3.0, it will help you to set the Bootloader when creating the sample program the burning file is also created together.

(2) After testing, it is indeed impossible to downgrade. It may be locked for security, but it is not very beneficial to our testers. At present, I have no good way.

**Comment by SYESHASWINI** [comment]
Tested with Secure fw version:2.2.0 and GSDK is 4.1.1. I have taken bootloader sample from the demo applications.

**Comment by SYESHASWINI** [comment]
Tried with the demo applications. I uploaded the demo on/off project and launched the console. Restarted the device, but it seems the project is not working as the leds are glowing. Using development kit with ZGM230S radio board.
![image](https://github.com/SiliconLabs/gecko_sdk/assets/59026832/4178f6d3-1028-45d9-9431-68f87fd7a311)

**Comment by SYESHASWINI** [comment]
I'm able build my application by flashing the demo bootloader and the my application makes it work
