### ISSUE TITLE
Increasing No.of Endpoints

### ISSUE THREAD

**Issue by SYESHASWINI** [SiliconLabs/gecko_sdk#50]
I'm using Z-wave GSDK"v4.1.1 Sample example: Switch On/Off which is of one endpoint. I need one more endpoint Can I know where the code snippet can be taken care. I tried changing the no.of endpoint in config_app.h , but it didn't worked out.

**Comment by LanKuoWei** [comment]
This should mainly be the report of SDK Issue, if you have any problems and applications in use, you can go to the forum to ask, it will be more appropriate.
